src/ALZ/Assets/alz-bicep-config/v0.14.1-pre.config.json
src/ALZ/Private/Get-ALZBicepConfig.ps1
src/ALZ/Public/New-ALZEnvironment.ps1

Update to version v0.14.1-pre of the provider

Change version to v0.14.1-pre

---

.github/workflows/Prerelease.yml

A temporary change to allow us to publish alongside of some of the published test modules.

Allow the prerelease pipeline publish to forcibly push a published package

---

.github/prerelease-drafter.yml
.github/workflows/Release.yml

Release Drafter wasn't incrementing the version number and was colliding with previous created releases... 
Switching to $RESOLVED_VERSION to see if that helps.

Trying a different variable for version number

---

src/ALZ/Assets/alz-bicep-config/v0.14.0.config.json

Issue #, #51 
- Fixed the issue by adding in two new computed values to correlate to each parameter
- Changed alz bicep config for the soon to be new release
Testing Evidence: 

Bug: Fixed name of file and added new computedparams

---

src/ALZ.Settings.ps1
src/ALZ/Assets/alz-bicep-config/v0.14.0.config.json

Issue #, if available: #53 
Description of changes: 
- Add fix for resource group name reference for LAW id
- Change supported ALZ version to v0.14.0

Bug: Fix for incorrect rg ref in LAW id

---

src/ALZ/Assets/alz-bicep-config/v0.14.0.config.json

N/A 
fix min prefix length from 3 to 2

fix min prefix length from 3 to 2

---

src/ALZ.Settings.ps1
src/ALZ/Assets/alz-bicep-config/v0.16.0.config.json
src/ALZ/Private/Get-ALZBicepConfig.ps1
src/ALZ/Public/New-ALZEnvironment.ps1

Added config and updated relevant files for v0.16.0 ALZ-Bicep release
Description of changes: 
-Added config and updated relevant files for v0.16.0 ALZ-Bicep release
-Adjusted file paths for new pipeline names within ALZ-Bicep

Added v0.16.0 config and updated references

---

README.md
src/ALZ/ALZ.psd1
src/ALZ/ALZ.psm1
src/ALZ/Public/Edit-LineEnding.ps1
src/ALZ/Public/Test-ALZRequirement.ps1
src/PSScriptAnalyzerSettings.psd1
src/Tests/Unit/ExportedFunctions.Tests.ps1
src/Tests/Unit/Private/Test-ALZRequirement.Tests.ps1
src/Tests/Unit/Public/Edit-LineEnding.Tests.ps1
src/Tests/Unit/Public/Test-ALZRequirement.Tests.ps1

Add alias of `Edit-LineEndings` for `Edit-LineEnding` and VS Code check

add alias and check for VS Code

---

src/ALZ.Settings.ps1
src/ALZ/Assets/alz-bicep-config/v0.16.2.config.json
src/ALZ/Private/Get-ALZBicepConfig.ps1
src/ALZ/Public/New-ALZEnvironment.ps1

Release v0.16.2 of ALZ Bicep

---

src/ALZ.Settings.ps1
src/ALZ/Assets/alz-bicep-config/v0.16.3.config.json
src/ALZ/Private/Get-ALZBicepConfig.ps1
src/ALZ/Public/New-ALZEnvironment.ps1

0.16.3 readiness

---

src/ALZ/Private/Invoke-Terraform.ps1
src/ALZ/Private/New-ALZEnvironmentTerraform.ps1
src/ALZ/Public/New-ALZEnvironment.ps1

N/A
This PR adds the capability to override the Terraform approval step. This is to support automated testing, but may also benefit customers.

Feature: add auto-approve for terraform

---

src/ALZ.Settings.ps1
src/ALZ/Assets/alz-bicep-config/v0.16.4.config.json
src/ALZ/Private/Get-ALZConfig.ps1
src/ALZ/Public/New-ALZEnvironment.ps1

N/A
Description of changes: Adding necessary config and config changs assocaited to a new release of ALZ-Bicep (v0.16.4)

Include ALZ-Bicep v0.16.4 config changes

---

src/ALZ.Settings.ps1
src/ALZ/Assets/alz-bicep-config/v0.16.5.config.json
src/ALZ/Private/Get-ALZConfig.ps1
src/ALZ/Public/New-ALZEnvironment.ps1

Updates for ALZ Bicep v0.16.5

---

src/ALZ.Settings.ps1
src/ALZ/Private/Build-ALZDeploymentEnvFile.ps1
src/ALZ/Private/New-ALZEnvironmentBicep.ps1

Issue #, if available: https://github.com/Azure/ALZ-Bicep/issues/684
This PR fixes an issue related to a hard coded version number in the Bicep accelerator. The hard coded version number will be removed in a separate PR, but this fix will work for the existing issue and once it is removed.

bug: upstream release version env var

---

src/ALZ/Private/New-ALZEnvironmentTerraform.ps1

Fixing the following error for the `terraform` deployment.

fix: add condition for `latest`

---

src/ALZ/Private/New-ALZEnvironmentTerraform.ps1

This PR fixes a bug where the auto approve parameter is not being passed to the function that gets the variables. This is causing the module to prompt for user input when it should not.

bug: fix missing auto approve flag

---

src/ALZ/Private/New-FolderStructure.ps1
src/ALZ/Public/New-ALZEnvironment.ps1

This is a bug fix for the override folder parameters. These are only required for e2e testing or customisation.

Fix local override folder function

---

src/ALZ/Private/Legacy-Bicep/New-ALZEnvironmentBicep.ps1

N/A
Fix an incorrect path
You can see the Bicep tests passing here: https://github.com/Azure/accelerator-bootstrap-modules/actions/runs/8375595350

Fix bug in bicep path

---

src/ALZ/Private/Deploy-Accelerator-Helpers/Invoke-FullUpgrade.ps1
src/ALZ/Private/Deploy-Accelerator-Helpers/Invoke-Upgrade.ps1
src/ALZ/Private/Deploy-Accelerator-Helpers/New-Bootstrap.ps1

This change improves the upgrade process to be able to auto upgrade the bootstrap and starter modules independently.

enhancement: support separate starter module upgrade

---

CONTRIBUTING.md

Update contribution guidance for local dev cycle

---

CONTRIBUTING.md
docs/wiki/[User-Guide]-Quick-Start-Phase-2-Azure-DevOps.md
docs/wiki/[User-Guide]-Quick-Start-Phase-2-GitHub.md
docs/wiki/[User-Guide]-Quick-Start-Phase-2-Local.md
docs/wiki/[User-Guide]-Starter-Module-Terraform-Complete-Multi-Region.md
docs/wiki/[User-Guide]-Starter-Module-Terraform-Complete.md
docs/wiki/_Sidebar.md
docs/wiki/examples/powershell-inputs/inputs-azure-devops-terraform-complete-multi-region.yaml
docs/wiki/examples/powershell-inputs/inputs-github-terraform-complete-multi-region.yaml
docs/wiki/examples/powershell-inputs/inputs-local-terraform-complete-multi-region.yaml
docs/wiki/examples/starter-module-config/complete-multi-region/config-hub-and-spoke-vnet.yaml
docs/wiki/examples/starter-module-config/complete-multi-region/config-virtual-wan.yaml
src/ALZ/Private/Config-Helpers/Remove-TerraformMetaFileSet.ps1
src/ALZ/Private/Deploy-Accelerator-Helpers/New-Bootstrap.ps1

N/A
Part of the Terraform multi-region support
e2e tests: https://github.com/Azure/accelerator-bootstrap-modules/actions/runs/11056162578

feat: multi region support for terraform

---

.github/workflows/Prerelease.yml
.github/workflows/Release.yml

chore: fix release process

---

.github/workflows/Prerelease.yml
.github/workflows/Release.yml

This reverts commit 9d965f37f704550aa2a30759946f03ae1956d770.

chore: revert - chore try to fix release process (#198)

---

docs/wiki/examples/powershell-inputs/inputs-azure-devops-terraform-basic.yaml
docs/wiki/examples/powershell-inputs/inputs-azure-devops-terraform-complete-vnext.yaml
docs/wiki/examples/powershell-inputs/inputs-azure-devops-terraform-hubnetworking.yaml
docs/wiki/examples/powershell-inputs/inputs-github-terraform-basic.yaml
docs/wiki/examples/powershell-inputs/inputs-github-terraform-complete-vnext.yaml
docs/wiki/examples/powershell-inputs/inputs-github-terraform-hubnetworking.yaml
docs/wiki/examples/powershell-inputs/inputs-local-terraform-basic.yaml
docs/wiki/examples/powershell-inputs/inputs-local-terraform-complete-vnext.yaml
docs/wiki/examples/powershell-inputs/inputs-local-terraform-hubnetworking.yaml

Some example input config files had incorrect starter_module_name specified.

fix: examples docs

---

docs/wiki/[User-Guide]-Quick-Start-Phase-2-Azure-DevOps.md
docs/wiki/[User-Guide]-Quick-Start-Phase-2-GitHub.md
docs/wiki/[User-Guide]-Quick-Start-Phase-2-Local.md

Add missing links for Terraform multi-region module

docs: missing docs multi region link

---

docs/wiki/[User-Guide]-Starter-Module-Terraform-Sovereign-Landing-Zone.md

Update SLZ input yaml file links.
Fix the input yam file links.
Update SLZ input yaml file links.

fix: update slz input yaml file links

---

docs/wiki/examples/powershell-inputs/inputs-azure-devops-terraform-sovereign-landing-zone.yaml
docs/wiki/examples/powershell-inputs/inputs-github-terraform-sovereign-landing-zone.yaml
docs/wiki/examples/powershell-inputs/inputs-local-terraform-sovereign-landing-zone.yaml

fix: Update slz input yaml files.

---

src/ALZ/Private/Config-Helpers/Write-TfvarsJsonFile.ps1

If a variable has a default of null and it is not supplied we see an error in the logs.

fix: null configuration value

---

docs/wiki/Frequently-Asked-Questions.md

https://github.com/Azure/ALZ-PowerShell-Module/issues/226
226

docs: fix the link to the upgrade guide

---

docs/wiki/Upgrade-Guide.md

No related issue
Fixed some minor typos in Upgrade-Guide Wiki page

docs: fixed some minor typos in upgrade-guide

---

src/ALZ/Private/Deploy-Accelerator-Helpers/New-Bootstrap.ps1

Add submodule support for starter modules
N/A
N/A
e2e tests running here: https://github.com/Azure/accelerator-bootstrap-modules/actions/runs/11487105261

feat: add submodule support

---

docs/wiki/examples/powershell-inputs/inputs-azure-devops-terraform-financial-services-landing-zone.yaml
docs/wiki/examples/powershell-inputs/inputs-azure-devops-terraform-sovereign-landing-zone.yaml
docs/wiki/examples/powershell-inputs/inputs-github-terraform-financial-services-landing-zone.yaml
docs/wiki/examples/powershell-inputs/inputs-github-terraform-sovereign-landing-zone.yaml
docs/wiki/examples/powershell-inputs/inputs-local-terraform-financial-services-landing-zone.yaml
docs/wiki/examples/powershell-inputs/inputs-local-terraform-sovereign-landing-zone.yaml

Fix missing input for FSI and SLZ.
These files will be removed next week when we release vNext, but just keeping them aligned for now.
[Issue #, if available:](https://github.com/Azure/ALZ-PowerShell-Module/issues/267)

fix: missing slz fsi input

---

src/ALZ/Private/Deploy-Accelerator-Helpers/Invoke-Terraform.ps1

azurerm v4 requires ARM_SUBSCRIPTION_ID env var to be set

feat: support azurerm v4

---

src/ALZ/Private/Deploy-Accelerator-Helpers/Invoke-Terraform.ps1

Fixes error unsetting arm subscription

fix: unsetting arm subscription

---

.github/workflows/Prerelease.yml
.github/workflows/Release.yml

upload-artifact has been deprecated and needs updating

fix: actions

---

README.md

#322 
One character fix. (The PowerShell function is not plural).

fix: Function is Test-AcceleratorRequirement not Test-AcceleratorRequirements

---

src/ALZ/ALZ.psd1
src/ALZ/Public/Invoke-EABillingSPNPermissionsSetup.ps1

Move the dependency on AZ PowerShell to only be in the function that needs it.

fix: az powershell dependency

---

src/ALZ/Private/Config-Helpers/Get-AzureRegionData.ps1

Issue #351
change Azure/avm-utl-regions/azurerm from 0.5.1 to 0.5.2

fix: geography and geography group may be null
