src/ALZ/Assets/alz-bicep-config/v0.14.1-pre.config.json
src/ALZ/Private/Edit-ALZConfigurationFilesInPlace.ps1
src/Tests/Unit/Private/Edit-ALZConfigurationFilesInPlace.Tests.ps1

#3 
#23 
Adding functionality to modify values before they're set based on simple PowerShell expressions...
This might be questionable - but I couldn't think of another way to easily deal with lots of situations where logic would need to be executed in response to user input.

Fixing bugs with complex value replacement needed.

---

src/ALZ/Assets/alz-bicep-config/v0.14.1-pre.config.json
src/ALZ/Private/Build-ALZDeploymentEnvFile.ps1
src/ALZ/Private/Edit-ALZConfigurationFilesInPlace.ps1
src/Tests/Unit/Private/Build-ALZDeploymentEnvFile.Tests.ps1
src/Tests/Unit/Private/Edit-ALZConfigurationFilesInPlace.Tests.ps1

Adding Computed values to Environment, also adding file targeted config to ALZ-BICEP-CONFIG
Fixes #38
Handling 'Computed' values for the Environment file.  (This needs a refactor of how we handle computed values, which I'll do after this change #40)
Supporting file specific replacement values with configuration.
```
{
Name = {Name of the setting in Bicep config or Environment}
File = {FileName}
Destination = {Parameters|Environment}
}
```

Handling File Targeted Configuration and fixing Environment Computed Values

---

src/ALZ/Assets/alz-bicep-config/v0.14.1-pre.config.json
src/ALZ/Private/New-ALZDirectoryEnvironment.ps1

General adjustments for ALZ Bicep Accelerator
- Need to adjust the policy assignment param file as switched to the ALZ defaults.
- Need to switch to orchestration version of management diagnostic setting module param file.
- Switching custom modules directory to match naming convention of custom parameters directory.

Updates for ALZ Bicep Accelerator

---

src/ALZ/Assets/alz-bicep-config/v0.14.1-pre.config.json
src/Tests/Unit/Private/Edit-ALZConfigurationFilesInPlace.Tests.ps1
src/Tests/Unit/Private/Request-ALZEnvironmentConfig.Tests.ps1

Issue #, if available: #48
- Remove management group suffix input requirement due to limitations with dependent ALZ-Bicep modules
- General formatting fixes for related files

Remove ALZ management group suffix references

---

src/ALZ/Assets/alz-bicep-config/v0.14.1-pre.config.json
src/ALZ/Private/Get-ALZBicepConfig.ps1
src/ALZ/Public/New-ALZEnvironment.ps1

Issue #, if available: NA
Description of changes: Changed the ALZ Bicep release version references from v0.14.1-pre to v0.14.0

Prep for alz bicep v0.14.0 release

---

README.md
src/ALZ/ALZ.psd1
src/ALZ/Public/Get-ALZGithubRelease.ps1
src/ALZ/Public/New-ALZEnvironment.ps1
src/Tests/Unit/Public/Get-ALZGithubRelease.Tests.ps1
src/Tests/Unit/Public/New-ALZEnvironment.Tests.ps1

Issue #, if available: #46
Makes GitHub-ReleaseFetcher public
-Makes GitHub-ReleaseFetcher public and function and associated references with ALZ to avoid conflicts
-General formatting adjustments
Tested evidence:

Changes for making the release fetcher script public

---

src/ALZ/Assets/alz-bicep-config/v0.14.0.config.json
src/Tests/Unit/Private/Request-ConfigurationValue.Tests.ps1

Issue #57 
The current regex does not allow a management group id like *iac-alz*.

management group id check

---

src/ALZ/Assets/alz-bicep-config/v0.14.0.config.json

Hub network deployment failing as its passing an array rather than a string.
Affected params are parHubNetworkName and parAzFirewallName
Amended code to declare a string rather than an array. Tested manually by updating the code on the fly.

Bug: Amended network params

---

src/ALZ/ALZ.psd1
src/ALZ/Public/Edit-LineEnding.ps1
src/Tests/Unit/Public/Edit-LineEnding.Tests.ps1

As part of simplifying ALZ Bicep users experiences with custom policies, I have added the `Edit-LineEnding` function from the `ALZ.Tools` local module in the `Azure/Enterprise-Scale` module to this module as a public function. Therefore any customer using the `ALZ` module, here, will automatically have it available to them without having to install another module
https://github.com/Azure/ALZ-Bicep/issues/583

Add edit-lineendings function

---

src/ALZ/Private/Get-HCLParserTool.ps1
src/ALZ/Public/New-ALZEnvironment.ps1

Issue #, if available: #71, #73, and #74
Description of changes: Fix issues with downloading the HCL parser and running it on MacOS and Linux. Also solve a potential issue where Terraform runs despite bicep being selected.

bug: fix switch and os selector

---

src/ALZ/Private/New-ALZEnvironmentTerraform.ps1
src/ALZ/Private/Request-ALZEnvironmentConfig.ps1
src/ALZ/Private/Request-ConfigurationValue.ps1
src/ALZ/Public/Get-ALZGithubRelease.ps1

Description of changes: 
For Terraform there are some cases where we want to either provide an empty value or a valid string. E.g. an empty string or a subscription id. The existing implementation did not handle this, so added a parameter to support this scenario.

feature: treat empty default as valid

---

README.md
src/ALZ/Private/New-ALZEnvironmentBicep.ps1
src/ALZ/Private/New-ALZEnvironmentTerraform.ps1
src/ALZ/Public/Get-ALZGithubRelease.ps1
src/ALZ/Public/New-ALZEnvironment.ps1
src/Tests/Unit/Public/Get-ALZGithubRelease.Tests.ps1

Issue #, if available: https://github.com/Azure/ALZ-Bicep/issues/691
Updated and simplified the method for updating to a newer version. Included an facility to automatically update the `.env` file.
There is an associated PR to update the docs: https://github.com/Azure/ALZ-Bicep/pull/692
- The `Get-ALZGithubRelease` function now requires the `IaC` parameter to be set to `bicep` or `terraform`.

enhancement: env file version automation

---

src/ALZ/Private/Get-ALZConfig.ps1
src/ALZ/Private/Invoke-Terraform.ps1
src/ALZ/Private/Invoke-Upgrade.ps1
src/ALZ/Private/New-ALZEnvironmentTerraform.ps1
src/ALZ/Private/Request-ALZEnvironmentConfig.ps1
src/ALZ/Private/Write-ConfigurationCache.ps1
src/ALZ/Public/New-ALZEnvironment.ps1
src/Tests/Unit/Public/New-ALZEnvironment.Tests.ps1

Issue #, if available: https://github.com/Azure/alz-terraform-accelerator/issues/70
This PR adds re-run, upgrade and destroy features for Terraform. These features are designed to simplify usage of the accelerator, provide any easy way to apply changes, fix issues and upgrade to a newer version. The destroy will make it much easier to clean up test environments.

Enhancement add terraform rerun and destroy

---

src/ALZ/Private/New-ALZEnvironmentTerraform.ps1
src/ALZ/Public/New-ALZEnvironment.ps1

Issue #, if available: https://github.com/Azure/alz-terraform-accelerator/issues/69
This removes the validation on the CI / CD variable for Terraform (Bicep retains it).
This is to support additional bootstrap types without needing to make changes to this module moving forwards.

feature: support `local` option for terraform

---

src/ALZ/Private/Test-ALZGitRepository.ps1

To align with https://github.com/github/renaming we have altered the `git init` logic.
This pull request introduces a change to the `Test-ALZGitRepository` function in the `src/ALZ/Private/Test-ALZGitRepository.ps1` file. The change adds a check for the `init.defaultbranch` git configuration variable to initialize the repository with the default branch set to "main" instead of "master" if necessary.
Main change:
* [`src/ALZ/Private/Test-ALZGitRepository.ps1`](diffhunk://#diff-f812e07345936b49445b2ee7a222296b624e8ec80605dda1ef252a819ebb8d57R17-R24): Added a check for the `init.defaultbranch` git configuration variable in the `Test-ALZGitRepository` function to initialize the repository with the default branch set to "main" instead of "master" if necessary.

Change `git init` logic

---

src/ALZ/Private/Convert-HCLVariablesToUserInputConfig.ps1
src/ALZ/Private/Import-ConfigurationFile.ps1
src/ALZ/Private/New-ALZEnvironmentTerraform.ps1
src/ALZ/Private/Request-ConfigurationValue.ps1
src/ALZ/Private/Write-ConfigurationCache.ps1
src/ALZ/Private/Write-TfvarsFile.ps1

This PR adds the ability to pass a config file path that is then included in the repository. This is to be more concise for users of the accelerator and only prompt for a config file if they are using a starter module that needs one. Also enables them to call the config file whatever name they desire.
This change has been tested and testing evidence can be found in the sister PR here: https://github.com/Azure/alz-terraform-accelerator/pull/89

Add config file specific code

---

src/ALZ/Private/Get-ALZConfig.ps1
src/ALZ/Private/Request-ConfigurationValue.ps1

- Reported by VBD team that the error message is not clear when invalid yaml or json are passed.
- The PAT is not masked when using cached values on a second run.

enhacement: add better error handling and masking for inputs

---

src/ALZ/Private/Config-Helpers/Add-AvailabilityZonesBicepParameters.ps1
src/ALZ/Private/Legacy-Bicep/New-ALZEnvironmentBicep.ps1
src/Tests/Unit/Private/Add-AvailabilityZonesBicepParameters.Tests.ps1

Issue #103 and #102
Adding a new private function to determine the availability zones for the selected regions and edit the parameters files of the relevant networking modules to include them by default.

Add availability zones Bicep parameter

---

src/ALZ/Private/Config-Helpers/Request-SpecialInput.ps1
src/ALZ/Private/Deploy-Accelerator-Helpers/Get-BootstrapAndStarterConfig.ps1
src/ALZ/Private/Deploy-Accelerator-Helpers/Get-StarterConfig.ps1
src/ALZ/Private/Deploy-Accelerator-Helpers/New-Bootstrap.ps1
src/ALZ/Private/Deploy-Accelerator-Helpers/New-FolderStructure.ps1
src/ALZ/Private/Deploy-Accelerator-Helpers/New-ModuleSetup.ps1
src/ALZ/Private/Shared/Get-GithubRelease.ps1
src/ALZ/Public/New-ALZEnvironment.ps1

#114 
This PR makes no significant functional changes other than improving the prompts users see for IaC, bootstrao and starter.
The primary update is to pull the bootstrap and starter from named artefacts. By doing this we can get some usage telemetry from the GitHub API.
Note that changes have been made to the starter and bootstrap repos for Terraform to accommodate this, but all those changes are backwards compatible and already released. They are ready to go with these changes now.
- E2E tests have be run for this branch here: https://github.com/Azure/accelerator-bootstrap-modules/actions/runs/9414281487
- Manual testing of Terraform and Bicep happy paths has been completed for prompt testing.
By submitting this pull request, I confirm that my contribution is made under the terms of …

Updates to support telemetry and better prompts

---

src/ALZ/Private/Deploy-Accelerator-Helpers/Get-BootstrapAndStarterConfig.ps1
src/ALZ/Private/Deploy-Accelerator-Helpers/New-Bootstrap.ps1
src/ALZ/Public/New-ALZEnvironment.ps1

We are removing a pipeline path variable that is no longer required.
Here is a successful e2e test run with the updated bootstrap code: https://github.com/Azure/accelerator-bootstrap-modules/actions/runs/9450687525/job/26029889532
These are the sister PRs related to this: 
* https://github.com/Azure/accelerator-bootstrap-modules/pull/23
* https://github.com/Azure/alz-terraform-accelerator/pull/152

Remove redundant pipeline variable

---

.github/workflows/super-linter.yml
.github/workflows/wiki-sync.yml

Add wiki workflows

---

src/ALZ/Private/Shared/Get-OsArchitecture.ps1

Add support for Windows arm64 emulation mode 

Support for Windows arm64

---

docs/wiki/examples/powershell-inputs/inputs-azure-devops-bicep.yaml
docs/wiki/examples/powershell-inputs/inputs-github-bicep.yaml
docs/wiki/examples/powershell-inputs/inputs-local-bicep.yaml

Fixes #126 
This pull request includes changes to three configuration files: `inputs-azure-devops-bicep.yaml`, `inputs-github-bicep.yaml`, and `inputs-local-bicep.yaml`. The changes are all similar, adjusting the `Prefix` value from "landing-zone" to "alz".
* [`docs/wiki/examples/powershell-inputs/inputs-azure-devops-bicep.yaml`](diffhunk://#diff-8ef51d276f1cb7be09e2f79aede3dbdee2557ca16dbfa2b61033ce601a45cc1dL37-R37): The `Prefix` value has been updated from "landing-zone" to "alz".
* [`docs/wiki/examples/powershell-inputs/inputs-github-bicep.yaml`](diffhunk://#diff-cd6e5c8c79a918b84fb1e835f52347eff7178a1714ead3c3461456520e591661L34-R34): The `Prefix` value has been updated from "landing-zone" to "alz".
* [`docs/wiki/examples/powershell-inputs/inputs-local-bicep.yaml`](diffhunk://#diff-65 …

fix: Correct issue with invalid default value for bicep configs

---

src/ALZ/Private/Config-Helpers/Write-TfvarsFile.ps1

Fixes #132 
This pull request includes significant enhancements to the `Write-TfvarsFile` function in the `Config-Helpers` module. The changes improve the handling of different data types when writing configuration values, ensuring that default values are used when necessary and that the correct format is applied for lists, maps, and objects.
* **Improved Handling of List Data Types**:
- Added a check for empty or null values and applied default values or an empty list (`[]`) as needed. (`src/ALZ/Private/Config-Helpers/Write-TfvarsFile.ps1`)
* **Added Support for Map Data Types**:
- Introduced logic to handle `map(string)` data types, ensuring that empty maps are represented as `{}` and non-empty maps are properly formatted. (`src/ALZ/Private/Config-Helpers/Write-TfvarsFile.ps1`)
* …

fix: Bug-132

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
docs/wiki/[User-Guide]-Quick-Start-Phase-2-Azure-DevOps.md
docs/wiki/[User-Guide]-Quick-Start-Phase-2-GitHub.md
docs/wiki/[User-Guide]-Quick-Start-Phase-2-Local.md
docs/wiki/[User-Guide]-Starter-Module-Bicep-Complete.md
docs/wiki/[User-Guide]-Starter-Module-Terraform-Basic.md
docs/wiki/[User-Guide]-Starter-Module-Terraform-Complete-VNext.md
docs/wiki/[User-Guide]-Starter-Module-Terraform-HubNetworking.md
docs/wiki/_Sidebar.md
docs/wiki/examples/powershell-inputs/inputs-azure-devops-bicep-complete.yaml
docs/wiki/examples/powershell-inputs/inputs-azure-devops-terraform-basic.yaml
docs/wiki/examples/powershell-inputs/inputs-azure-devops-terraform-complete-vnext.yaml
docs/wiki/examples/powershell-inputs/inputs-azure-devops-terraform-complete.yaml
docs/wiki/examples/powershell-inputs/inputs-azure-devops-terraform-hubnetworking.yaml
docs/wiki/examples/powershell-inputs/inputs-github-bicep-complete.yaml
docs/wiki/examples/powershell-inputs/inputs-github-terraform-basic.yaml
docs/wiki/examples/powershell-inputs/inputs-github-terraform-complete-vnext.yaml
docs/wiki/examples/powershell-inputs/inputs-github-terraform-complete.yaml
docs/wiki/examples/powershell-inputs/inputs-github-terraform-hubnetworking.yaml
docs/wiki/examples/powershell-inputs/inputs-local-bicep-complete.yaml
docs/wiki/examples/powershell-inputs/inputs-local-terraform-basic.yaml
docs/wiki/examples/powershell-inputs/inputs-local-terraform-complete-vnext.yaml
docs/wiki/examples/powershell-inputs/inputs-local-terraform-complete.yaml
docs/wiki/examples/powershell-inputs/inputs-local-terraform-hubnetworking.yaml

#159
This PR fixes the documentation for Terraform starter modules

Enhancement - Fix Terraform starter module docs and samples

---

docs/wiki/[User-Guide]-Quick-Start-Phase-3.md

Issue #, if available: #158
This PR updates the docs for local to ensure it can connect to the deployed storage account via Entra ID auth.

Docs: Update local steps to use azure ad auth

---

docs/wiki/examples/starter-module-config/complete/config-hub-spoke.yaml
docs/wiki/examples/starter-module-config/complete/config-vwan.yaml

This updates the `complete` config examples to use the correct location variable name.

docs: fix variable name in config examples

---

src/ALZ/Private/Config-Helpers/Write-TfvarsJsonFile.ps1
src/ALZ/Private/Deploy-Accelerator-Helpers/New-Bootstrap.ps1

Issue #212 
Resolve issue with exporting true boolean valued variables to TF VARS file.

fix: boolean true output issue

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Update the issue templates to make it clear which starter module they are for.

chore: issue template improvement

---

docs/wiki/examples/starter-module-config/complete-multi-region/config-hub-and-spoke-vnet-multi-region.yaml
docs/wiki/examples/starter-module-config/complete-multi-region/config-hub-and-spoke-vnet-single-region.yaml
docs/wiki/examples/starter-module-config/complete-multi-region/config-virtual-wan-multi-region.yaml
docs/wiki/examples/starter-module-config/complete-multi-region/config-virtual-wan-single-region.yaml

Missing management resource deployment in default examples.

fix: add missing management resources for exmaples

---

docs/wiki/examples/starter-module-config/complete-multi-region/config-hub-and-spoke-vnet-multi-region.yaml
docs/wiki/examples/starter-module-config/complete-multi-region/config-hub-and-spoke-vnet-single-region.yaml
docs/wiki/examples/starter-module-config/complete-multi-region/config-virtual-wan-multi-region.yaml
docs/wiki/examples/starter-module-config/complete-multi-region/config-virtual-wan-single-region.yaml

Add corp and online to the example landing zone config

fix: missing corp and online in default examples

---

docs/wiki/[User-Guide]-Starter-Module-Terraform-Sovereign-Landing-Zone.md

fix: Update the location after using the starter_locations instead of the default location.

fix: Update for location.

---

docs/wiki/[User-Guide]-Starter-Module-Terraform-Financial-Services-Industry-Landing-Zone.md
docs/wiki/[User-Guide]-Starter-Module-Terraform-Sovereign-Landing-Zone.md

Fix the typo for display name in doc.

fix: update display name in doc

---

src/ALZ/Private/Config-Helpers/Convert-ParametersToInputConfig.ps1
src/ALZ/Private/Config-Helpers/Get-ALZConfig.ps1
src/ALZ/Private/Config-Helpers/Remove-TerraformMetaFileSet.ps1
src/ALZ/Private/Config-Helpers/Request-SpecialInput.ps1
src/ALZ/Private/Config-Helpers/Set-Config.ps1
src/ALZ/Private/Config-Helpers/Write-TfvarsJsonFile.ps1
src/ALZ/Private/Deploy-Accelerator-Helpers/Get-BootstrapAndStarterConfig.ps1
src/ALZ/Private/Deploy-Accelerator-Helpers/New-Bootstrap.ps1
src/ALZ/Public/New-ALZEnvironment.ps1

There are three key features implemented here:
- Support tfvars as an input format.
- Support tfvars pass through for Terraform starter modules in order to provide a good experience for customers with day 2 operations.
- Support supplying a lib folder (or any arbitrary files or folders) to support vNext customisation.
End to end tests will be run to confirm there are no breaking changes.
e2e test run is here: https://github.com/Azure/accelerator-bootstrap-modules/actions/runs/11955283956

feat: support tfvars for inputs and lib for vnext

---

src/ALZ/Private/Config-Helpers/Get-AzureRegionData.ps1

#213 
Fix the regions provider version and use the AVM
e2e test run for this branch: https://github.com/Azure/accelerator-bootstrap-modules/actions/runs/12273987111

fix: regions provider version

---

src/ALZ/Private/Config-Helpers/Get-AzureRegionData.ps1

https://github.com/Azure/ALZ-Bicep/issues/939
Fix the data type of availability zones as Bicep is expecting an array of strings

fix: availability zone data type

---

src/ALZ/ALZ.psd1

https://github.com/Azure/ALZ-PowerShell-Module/issues/232
Add properties to the manifiest to block installation on `desktop` PowerShell

feat: only allow powershell core

---

src/ALZ/Private/Deploy-Accelerator-Helpers/Invoke-Terraform.ps1
src/ALZ/Private/Tools/Test-Tooling.ps1

Support SP auth and skip az cli checks. Issue spotted in e2e tests.

fix: support sp auth for requirements

---

.github/workflows/PullRequest.yml
CONTRIBUTING.md
src/ALZ/Private/Tools/Test-Tooling.ps1
src/ALZ/Public/Deploy-Accelerator.ps1
src/ALZ/Public/Test-AcceleratorRequirement.ps1

Add the ability to skip the alz module version check, but retain the other checks.
This primarily for local development and e2e tests.

feat: alz version check skip

---

src/ALZ/Private/Tools/Get-TerraformTool.ps1

Issue #, if available: https://github.com/Azure/ALZ-PowerShell-Module/issues/311
HashiCorp updated their release website such that the version string no longer matches. This PR removes the `v` from the version number to make it work again.

fix: terraform tool download

---

src/ALZ/Private/Config-Helpers/Get-AzureRegionData.ps1

Issue #351 
Change version of avm-utl-regions to 0.5.1 to avoid empty value of geographyGroup of metadata

fix: avoid empty value of geographyGroup of metadata

---

src/ALZ/Private/Shared/Get-GithubRelease.ps1

replace "transient" with "transient" in the message displayed when fetching the GitHub release returns an error

fix: spelling error when retrieving github release returns an error

---

src/ALZ/Private/Deploy-Accelerator-Helpers/Invoke-Terraform.ps1

Fixes #389
Expands ~ with $env:HOME if found in moduleFolderPath

fix: Expand tilde for chdir (issue #389)

---

src/ALZ/Private/Config-Helpers/Set-Config.ps1

Issue #412 
Solve all collection input issues for Bicep

fix: collection types

---

src/ALZ/Private/Config-Helpers/Set-Config.ps1

Issue #, if available: https://github.com/Azure/ALZ-PowerShell-Module/issues/412#issuecomment-3314146600
PowerShell Convert commands unboxes single item arrays, we need to handle that for the single item array (e.g. single region)

fix: handle single item array
